### PR TITLE
Check if path is a subvolume when filesystem is btrfs

### PR DESCRIPTION
**Pull request by EnderShadow**
Fix for issue #180

### CODE REVIEW

**Comment by EnderShadow** [comment]
The reason I made the change that I did is becuase `get_fs_type()` isn't correctly returning whether or not the path is a btrfs subvolume. My change identifies whether or not the path is a btrfs subvolume. The main issue with the code prior to the patch is that it doesn't realize that the path is a subvolume and so it tries to create a subvolume on top of it.

**Comment by Jarel1337** [comment]
No I understand. I want the patch to be a bit "cleaner". The issue here stems from the path the we try to create a btrfs subvolume if one doesn't exist *even* if it is not possible to do so. I'd propose creating a new function `subvolume_possible` that we run on [L171](https://github.com/Nefelim4ag/systemd-swap/blob/90af95f5251c8cdb4820e24e758b56c357aff9bf/systemd-swap#L171)

**Review by Jarel1337 — CHANGES_REQUESTED** [review]
No I understand. I want the patch to be a bit "cleaner". The issue here stems from the path the we try to create a btrfs subvolume if one doesn't exist even if it is not possible to do so. I'd propose creating a new function subvolume_possible that we run on [L171](https://github.com/Nefelim4ag/systemd-swap/blob/90af95f5251c8cdb4820e24e758b56c357aff9bf/systemd-swap#L171)

**Comment by EnderShadow** [comment]
I've updated it so it uses the suggested function instead.

**Pull request merged**
